/**
 * seed-capabilities-cards.ts — 种子能力卡内容（与导入逻辑分离，各自守住行数上限）
 *
 * 覆盖高频办公场景。内容纪律：每条步骤必须与当前工具能力对齐
 * （常驻：mouse_click/hover/drag/scroll/hold、keyboard_type/press、open_app、
 * activate_window、剪贴板、ui_locate/ui_click、file_read/write/list；
 * 可选需 request_tools：ui_scroll_to、web_search、look_close、wait、excel_*、
 * wechat_send、screen_ocr、wait_for）——做不到的一律不写。
 * 描述里保留完整的 3+ 字中文短语，保证 trigram FTS 对真实查询词的召回。
 */
import type { CapabilityCreateRequest } from '../../shared/schemas/capability';

/** 种子能力卡定义 */
export const SEED_CAPABILITIES: CapabilityCreateRequest[] = [
  // ---------- 既有种子（9 张） ----------
  {
    id: 'cap.excel.fill_column',
    title: '填充 Excel 列',
    description: '当用户需要将一列单元格按规则填充（如序号、公式、日期）时使用此能力卡。',
    tools: ['excel_read_range', 'excel_write_cell', 'ui_locate', 'ui_click'],
    precondition: '已打开目标 Excel 文件且目标列已确定',
    acceptance: '目标列所有行已正确填充，无空行遗漏',
    visualAnchors: [],
  },
  {
    id: 'cap.excel.read_table',
    title: '读取 Excel 表格',
    description: '从 Excel 区域中读取数据，转换为结构化表格供后续处理。',
    tools: ['excel_read_range', 'file_read'],
    precondition: '已打开目标 Excel 文件',
    acceptance: '成功读取指定区域的所有数据行',
    visualAnchors: [],
  },
  {
    id: 'cap.files.organize',
    title: '整理文件夹',
    description: '按规则（日期、类型、名称）将文件移动到对应子文件夹中。',
    tools: ['file_list', 'file_read', 'file_write'],
    precondition: '目标文件夹存在且可写',
    acceptance: '所有文件已按规则归入对应子文件夹',
    visualAnchors: [],
  },
  {
    id: 'cap.files.batch_rename',
    title: '批量重命名文件',
    description: '按命名规则（如日期前缀、序号、模板替换）对多个文件进行重命名。',
    tools: ['file_list', 'file_read', 'file_write'],
    precondition: '目标文件夹存在且文件可重命名',
    acceptance: '所有匹配文件已按规则重命名完成',
    visualAnchors: [],
  },
  {
    id: 'cap.app.launch_and_login',
    title: '启动应用并登录',
    description: '打开指定应用，若需要登录则完成登录流程（输入账号密码、处理验证码等）。',
    tools: ['open_app', 'activate_window', 'ui_locate', 'ui_click', 'keyboard_type'],
    precondition: '目标应用已安装，账号凭据已准备',
    acceptance: '应用已启动并处于已登录状态',
    visualAnchors: [],
  },
  {
    id: 'cap.browser.search_and_extract',
    title: '浏览器搜索并提取信息',
    description: '在浏览器中执行搜索查询，从结果页面提取所需信息。',
    tools: ['open_app', 'ui_locate', 'ui_click', 'keyboard_type', 'get_clipboard'],
    precondition: '浏览器已安装且可用',
    acceptance: '成功提取所需搜索结果信息',
    visualAnchors: [],
  },
  {
    id: 'cap.office.copy_paste',
    title: '跨应用复制粘贴',
    description: '从源应用中复制数据，切换到目标应用并粘贴。',
    tools: ['ui_locate', 'ui_click', 'keyboard_press', 'get_clipboard', 'set_clipboard'],
    precondition: '源应用和目标应用均已打开',
    acceptance: '数据已从源应用复制并粘贴到目标应用',
    visualAnchors: [],
  },
  {
    id: 'cap.wechat.send_message',
    title: '发送微信消息',
    description: '通过微信发送消息给指定联系人或群组。',
    tools: ['wechat_send', 'ui_locate', 'ui_click', 'keyboard_type'],
    precondition: '微信已登录且目标联系人存在',
    acceptance: '消息已成功发送到目标联系人',
    visualAnchors: [],
  },
  {
    id: 'cap.generic.look_and_act',
    title: '查看画面并操作',
    description: '通用能力卡：截屏查看当前画面，定位 UI 元素，执行点击或输入操作。',
    tools: ['look_close', 'ui_locate', 'ui_click', 'keyboard_type', 'mouse_click', 'mouse_scroll'],
    precondition: '目标窗口已在前台显示',
    acceptance: '完成用户指定的操作目标',
    visualAnchors: [],
  },
  // ---------- Excel / Word ----------
  {
    id: 'cap.excel.open_and_read',
    title: '打开Excel并读取数据',
    description: 'open_app 传 xlsx 文件路径打开 Excel，wait_for 等窗口标题出现后优先用 excel_read_range 直接读区域；不知道路径时 file_list 在文档/下载目录找文件。',
    tools: ['open_app', 'wait_for', 'excel_read_range', 'file_list'],
    precondition: '目标 xlsx 文件存在且可打开',
    acceptance: '已读到目标工作表的指定区域数据',
    visualAnchors: [],
  },
  {
    id: 'cap.excel.formula_fill',
    title: 'Excel 公式求和计算',
    description: '对区域做公式计算：excel_write_cell 直接写 "=SUM(B2:B10)" 等公式；界面上则点击目标单元格 keyboard_type 输入公式后 Enter，选中文本范围可用 mouse_click(modifiers:["shift"])。',
    tools: ['excel_write_cell', 'excel_read_range', 'mouse_click', 'keyboard_type'],
    precondition: '目标工作表已打开且数据区域确定',
    acceptance: '公式单元格显示的计算结果与区域数据一致',
    visualAnchors: [],
  },
  {
    id: 'cap.excel.sheet_switch',
    title: 'Excel 切换与重命名工作表',
    description: '工作表标签在窗口底部：mouse_click 标签名切换；双击标签或选中后按 F2 重命名，输入新名 Enter 确认；标签过多时标签栏左右箭头上 ui_scroll_to/mouse_scroll。',
    tools: ['mouse_click', 'keyboard_press', 'keyboard_type', 'ui_locate', 'mouse_scroll'],
    precondition: 'Excel 已打开且存在多个工作表',
    acceptance: '活动工作表已切换或标签已按新名显示',
    visualAnchors: [],
  },
  {
    id: 'cap.excel.save_as_csv',
    title: 'Excel 另存为 CSV',
    description: 'Ctrl+S 触发保存；首次保存或需换格式时弹「另存为」对话框：文件名框 Alt+D 不可用时用 mouse_click 聚焦，格式下拉 mouse_click 展开选 CSV(逗号分隔)，Enter 确认；覆盖弹窗再 Enter。',
    tools: ['keyboard_press', 'mouse_click', 'ui_locate', 'ui_click', 'keyboard_type'],
    precondition: '目标工作簿已打开且有写权限',
    acceptance: '另存为对话框关闭且目标路径出现同名 csv 文件',
    visualAnchors: [],
  },
  {
    id: 'cap.excel.sort_filter',
    title: 'Excel 排序与筛选',
    description: '选中数据列（点击列头）后 Ctrl+Shift+L 开筛选，点击下拉箭头 mouse_click(modifiers:[]) 勾选筛选值 Enter；排序走 数据 选项卡 → ui_locate 查找「排序」按钮再点。',
    tools: ['mouse_click', 'keyboard_press', 'ui_locate', 'ui_click', 'excel_read_range'],
    precondition: '数据区域连续且有表头',
    acceptance: '筛选后仅可见目标行 / 排序后列值单调有序',
    visualAnchors: [],
  },
  {
    id: 'cap.word.save_and_saveas',
    title: 'Word 保存与另存为',
    description: '日常保存只按 Ctrl+S；首次保存弹另存为对话框：文件名框 keyboard_type 输入完整路径+文件名（或 set_clipboard 后 Ctrl+V 粘贴路径），Enter 确认，覆盖提示再 Enter。',
    tools: ['keyboard_press', 'keyboard_type', 'set_clipboard', 'mouse_click'],
    precondition: 'Word 文档已打开且目标目录可写',
    acceptance: '标题栏文件名已更新且磁盘文件时间戳刷新',
    visualAnchors: [],
  },
  {
    id: 'cap.word.find_replace',
    title: 'Word 查找替换',
    description: 'Ctrl+H 打开替换对话框 → mouse_click 定位「查找内容」「替换为」两输入框分别 keyboard_type → Enter（全部替换后确认弹窗再 Enter），Esc 关闭对话框。',
    tools: ['keyboard_press', 'mouse_click', 'ui_locate', 'ui_click', 'keyboard_type'],
    precondition: 'Word 文档处于编辑状态',
    acceptance: '全文已无查找词或替换处数符合预期',
    visualAnchors: [],
  },
  {
    id: 'cap.word.copy_paragraph',
    title: 'Word 选中段落并复制',
    description: '段落起点 mouse_click，终点 mouse_click(modifiers:["shift"]) 选中范围（整段 Ctrl+A 或点击段落左侧选定栏），Ctrl+C 复制，activate_window 切到目标窗口 Ctrl+V。',
    tools: ['mouse_click', 'keyboard_press', 'activate_window', 'get_clipboard', 'set_clipboard'],
    precondition: '源 Word 与目标应用均已打开',
    acceptance: '目标应用中出现与源段落一致的文本',
    visualAnchors: [],
  },
  {
    id: 'cap.word.export_pdf',
    title: 'Word 打印导出 PDF',
    description: 'Ctrl+P 打开打印面板 → ui_locate 打印机下拉选 "Microsoft Print to PDF" → 打印 → 弹另存为对话框输入文件名 Enter。',
    tools: ['keyboard_press', 'ui_locate', 'ui_click', 'mouse_click', 'keyboard_type'],
    precondition: 'Word 文档已打开且系统装有 Microsoft Print to PDF',
    acceptance: '目标路径生成同名 PDF 文件',
    visualAnchors: [],
  },
  // ---------- 资源管理器 ----------
  {
    id: 'cap.explorer.multi_select',
    title: '资源管理器多选文件',
    description: '不连续多选：先点第一个文件，再对每个目标 mouse_click(modifiers:["ctrl"])；连续范围：点首个后 mouse_click(modifiers:["shift"]) 点末个；全部 Ctrl+A。',
    tools: ['mouse_click', 'keyboard_press'],
    precondition: '目标文件夹已在资源管理器打开',
    acceptance: '选中文件数与目标清单一致',
    visualAnchors: [],
  },
  {
    id: 'cap.explorer.rename',
    title: '资源管理器重命名文件',
    description: '选中文件按 F2（或右键菜单选重命名）→ keyboard_type 输入新名 → Enter；弹「更改扩展名可能不可用」提示时 Enter 确认。',
    tools: ['mouse_click', 'keyboard_press', 'keyboard_type'],
    precondition: '目标文件可见且未被占用',
    acceptance: '文件列表中显示新文件名',
    visualAnchors: [],
  },
  {
    id: 'cap.explorer.goto_path',
    title: '地址栏跳转到指定路径',
    description: '资源管理器按 Alt+D 聚焦地址栏（内容自动全选）→ keyboard_type 或 set_clipboard+Ctrl+V 输入目标路径 → Enter 直达；Win+E 可先打开资源管理器。',
    tools: ['keyboard_press', 'keyboard_type', 'set_clipboard', 'open_app'],
    precondition: '目标路径真实存在',
    acceptance: '窗口标题/地址栏显示目标路径',
    visualAnchors: [],
  },
  {
    id: 'cap.explorer.search_files',
    title: '资源管理器搜索文件',
    description: '进入含子目录的文件夹后 Ctrl+F（或点右上角搜索框）聚焦 → keyboard_type 关键词 → Enter；等结果用 wait_for(text) 或画面稳定，再 mouse_click 双击打开命中文件。',
    tools: ['keyboard_press', 'keyboard_type', 'wait_for', 'mouse_click'],
    precondition: '搜索范围文件夹已打开',
    acceptance: '列表出现匹配文件且名称包含关键词',
    visualAnchors: [],
  },
  {
    id: 'cap.explorer.new_folder',
    title: '新建文件夹并移入文件',
    description: '目标目录内 Ctrl+Shift+N 新建 → 直接 keyboard_type 命名 Enter → 选文件 mouse_drag_hold 拖入文件夹；拖不动就 Ctrl+X 剪切后进入文件夹 Ctrl+V。',
    tools: ['keyboard_press', 'keyboard_type', 'mouse_drag_hold', 'mouse_click'],
    precondition: '目标父目录可写',
    acceptance: '新文件夹存在且包含移入的文件',
    visualAnchors: [],
  },
  // ---------- 浏览器 ----------
  {
    id: 'cap.browser.search_query',
    title: '浏览器搜索关键词',
    description: 'open_app 打开浏览器 → Ctrl+L 或 Alt+D 聚焦地址栏 → keyboard_type 搜索词 → Enter → screen_ocr 或 look_close 读结果页文本。',
    tools: ['open_app', 'keyboard_press', 'keyboard_type', 'screen_ocr', 'look_close'],
    precondition: '网络可用且浏览器已安装',
    acceptance: '结果页已展示与搜索词相关的内容',
    visualAnchors: [],
  },
  {
    id: 'cap.browser.download_file',
    title: '浏览器下载文件',
    description: '定位下载链接 mouse_click（弹「另存为」则 set_clipboard 粘贴目标路径后 Enter）→ 下载完成后看底部栏，或 Ctrl+J 打开下载页 wait_for(text) 等文件名出现核对状态。',
    tools: ['mouse_click', 'set_clipboard', 'keyboard_press', 'wait_for', 'screen_ocr'],
    precondition: '下载链接有效且目标目录可写',
    acceptance: '下载页显示已完成且文件存在于目标目录',
    visualAnchors: [],
  },
  {
    id: 'cap.browser.read_page',
    title: '读取网页正文内容',
    description: '要整页文字：Ctrl+A 选中 → Ctrl+C → get_clipboard 取回；要看局部小字：mouse_scroll 滚动或用 screen_ocr 读取指定区域。',
    tools: ['keyboard_press', 'get_clipboard', 'screen_ocr', 'mouse_scroll'],
    precondition: '页面已加载完成',
    acceptance: '已获取页面正文文本且无明显截断',
    visualAnchors: [],
  },
  // ---------- 微信 / 钉钉 ----------
  {
    id: 'cap.wechat.search_contact',
    title: '微信搜索联系人或群',
    description: '微信窗口激活后 Ctrl+F 聚焦搜索框 → keyboard_type 联系人/群名 → Enter 进会话；也可点击搜索结果第一项 mouse_click。',
    tools: ['activate_window', 'keyboard_press', 'keyboard_type', 'mouse_click'],
    precondition: '微信桌面端已登录',
    acceptance: '已进入目标联系人或群的会话窗口',
    visualAnchors: [],
  },
  {
    id: 'cap.wechat.send_file',
    title: '微信发送文件',
    description: '进入目标会话 → 点输入框上方文件夹图标（可 ui_locate 找「文件」）→ 文件选择对话框的「文件名」框 set_clipboard 粘贴文件完整路径 → Enter 打开 → 发送确认弹窗 Enter。发消息走 wechat_send 工具。',
    tools: ['ui_locate', 'ui_click', 'mouse_click', 'set_clipboard', 'keyboard_press', 'wechat_send'],
    precondition: '微信已登录且文件路径存在',
    acceptance: '会话记录出现该文件气泡（或 wechat_send 返回成功）',
    visualAnchors: [],
  },
  {
    id: 'cap.dingtalk.send_message',
    title: '钉钉发送消息',
    description: 'activate_window 到钉钉 → Ctrl+F 或点击搜索框 → keyboard_type 联系人名 → Enter 开会话 → mouse_click 消息输入框 → keyboard_type 内容（或 set_clipboard+Ctrl+V）→ Enter 发送。',
    tools: ['activate_window', 'keyboard_press', 'keyboard_type', 'mouse_click', 'set_clipboard'],
    precondition: '钉钉桌面端已登录且联系人存在',
    acceptance: '会话窗口出现已发送的消息气泡',
    visualAnchors: [],
  },
  {
    id: 'cap.dingtalk.send_file',
    title: '钉钉发送文件',
    description: '进入目标会话 → 输入框上方「文件夹/发送文件」图标 ui_locate 定位并点击 → 文件对话框「文件名」框粘贴完整路径 → Enter 选中 → 发送窗口 Enter 确认。',
    tools: ['ui_locate', 'ui_click', 'mouse_click', 'set_clipboard', 'keyboard_press'],
    precondition: '钉钉已登录且文件路径存在',
    acceptance: '会话中出现文件卡片且状态为发送成功',
    visualAnchors: [],
  },
  // ---------- 系统应用与工具 ----------
  {
    id: 'cap.notepad.write_save',
    title: '记事本写文本并保存',
    description: 'open_app("notepad") → keyboard_type 输入内容 → Ctrl+S；首次保存弹另存为：文件名框输入「完整路径+文件名」Enter。已知目标路径时优先 file_write 直写更稳。',
    tools: ['open_app', 'keyboard_type', 'keyboard_press', 'file_write'],
    precondition: '目标目录可写',
    acceptance: '磁盘上存在所保存的文件且内容一致',
    visualAnchors: [],
  },
  {
    id: 'cap.calc.compute',
    title: '计算器算式求值',
    description: 'open_app("calc") → 等窗口出现（wait_for）→ keyboard_type 输入算式（如 128*7）→ Enter → screen_ocr 读结果区数字回报。',
    tools: ['open_app', 'wait_for', 'keyboard_type', 'screen_ocr', 'ui_locate'],
    precondition: 'Windows 计算器可用',
    acceptance: '已读取到与算式一致的计算结果',
    visualAnchors: [],
  },
  {
    id: 'cap.screenshot.capture',
    title: '截图工具区域截取',
    description: 'keyboard_press("Win+Shift+S") 唤起截图条 → mouse_drag 拖选目标区域 → 自动进剪贴板 → 到目标应用（微信输入框/画图）Ctrl+V 粘贴；画图为 open_app("mspaint") 后粘贴再 Ctrl+S。',
    tools: ['keyboard_press', 'mouse_drag', 'keyboard_type', 'open_app', 'activate_window'],
    precondition: '屏幕目标区域可见',
    acceptance: '目标应用/文件中出现截取的画面内容',
    visualAnchors: [],
  },
  {
    id: 'cap.taskmgr.kill_process',
    title: '任务管理器结束进程',
    description: 'Ctrl+Shift+Esc 打开任务管理器 → ui_locate 进程名（列表长时 ui_scroll_to 滚到可见）→ mouse_click 选中后点「结束任务」或右键菜单选它 → 确认弹窗 Enter。属敏感操作会走审批。',
    tools: ['keyboard_press', 'ui_locate', 'ui_scroll_to', 'ui_click', 'mouse_click'],
    precondition: '目标进程正在运行且用户有权限终止',
    acceptance: '进程列表中不再出现目标进程',
    visualAnchors: [],
  },
  {
    id: 'cap.archive.extract',
    title: '解压压缩包',
    description: '资源管理器定位压缩包 → mouse_click 右键 → 菜单选「全部解压缩」（Win11 先点「更多选项」）→ 解压目标对话框 Enter 用默认，或改名后 Enter；wait_for 等进度完成。',
    tools: ['mouse_click', 'keyboard_press', 'keyboard_type', 'wait_for', 'file_list'],
    precondition: '压缩包路径存在',
    acceptance: '解压目录内文件数与压缩包内容一致',
    visualAnchors: [],
  },
  {
    id: 'cap.archive.compress',
    title: '压缩文件为 zip',
    description: '资源管理器 mouse_click(modifiers:["ctrl"]) 多选目标文件 → 右键 → 「发送到 → 压缩文件夹」(Win11 点「压缩为 ZIP 文件」) → 生成同名 zip 后可 F2 重命名。',
    tools: ['mouse_click', 'keyboard_press', 'keyboard_type'],
    precondition: '目标文件在同一可写目录',
    acceptance: '目录中出现包含所选文件的 zip 包',
    visualAnchors: [],
  },
  {
    id: 'cap.pdf.read',
    title: '阅读 PDF 文件',
    description: 'open_app 传 pdf 路径用默认阅读器打开 → wait_for 等窗口 → Page Down 翻页或 Ctrl+F 搜索关键词 → 需要文字时 screen_ocr 读当前页。',
    tools: ['open_app', 'wait_for', 'keyboard_press', 'screen_ocr', 'mouse_scroll'],
    precondition: 'PDF 文件存在且非损坏',
    acceptance: '已定位并读到目标页/目标关键词内容',
    visualAnchors: [],
  },
  {
    id: 'cap.app.uninstall',
    title: '卸载应用软件',
    description: '卸载软件走系统设置：open_app("ms-settings:appsfeatures") 打开「安装的应用」→ 列表内滚动找到应用名（ui_locate + ui_scroll_to，或搜索框 keyboard_type）→ 点「卸载」→ 确认对话框 Enter。卸载属敏感操作会走审批。',
    tools: ['open_app', 'ui_locate', 'ui_scroll_to', 'ui_click', 'keyboard_type', 'keyboard_press'],
    precondition: '目标应用已安装在系统中',
    acceptance: '应用列表不再显示该应用',
    visualAnchors: [],
  },
  {
    id: 'cap.settings.toggle',
    title: '系统设置项修改',
    description: 'open_app("ms-settings:") 或直达子页（ms-settings:display、ms-settings:notification）→ ui_locate 目标设置项 → ui_click 开关/下拉；找不到入口用设置首页搜索框 keyboard_type 关键词。',
    tools: ['open_app', 'ui_locate', 'ui_scroll_to', 'ui_click', 'keyboard_type'],
    precondition: '设置项允许当前用户修改',
    acceptance: '回到页面确认设置项已显示为新值',
    visualAnchors: [],
  },
  {
    id: 'cap.window.manage',
    title: '窗口切换排列与关闭',
    description: '多窗口重叠时 activate_window 按标题精确激活（比 Alt+Tab 连按可靠）；键盘路径 Alt+Tab 切换、Win+D 显示桌面、Alt+F4 关闭当前窗口，Ctrl+W 关标签页。',
    tools: ['activate_window', 'keyboard_press', 'ui_locate', 'mouse_click'],
    precondition: '目标窗口已存在',
    acceptance: '目标窗口处于前台且标题正确',
    visualAnchors: [],
  },
  {
    id: 'cap.files.clipboard_bridge',
    title: '用剪贴板跨应用搬运文本',
    description: '源应用 Ctrl+C 后 get_clipboard 取回文本（校验内容），目标应用 keyboard_type 直接输入，或 set_clipboard 预置内容后 activate_window+Ctrl+V 粘贴——长文本/多行优先走剪贴板。',
    tools: ['get_clipboard', 'set_clipboard', 'activate_window', 'keyboard_press'],
    precondition: '源与目标应用均可访问',
    acceptance: '目标应用中的文本与源内容一致',
    visualAnchors: [],
  },
];
